version: "3.8"
services:
  neo4j:
    image: neo4j:4.2
    volumes:
      - ./logs:/logs
      - ./data:/data
      - ./plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/testpass
      # - NEO4JLABS_PLUGINS=["apoc"]
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_import_file_use__neo4j__config=true
